name: Docker CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log into GitHub Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,enable={{is_default_branch}},value=latest,priority=1000
            type=raw,enable=true,value={{date 'YYYYMMDD-HHmmss' tz='UTC'}},priority=100
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-viaaas
            ghcr.io/${{ github.repository }}
            
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
